version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: shareit-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: share_it
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d share_it"]
      interval: 5s
      timeout: 5s
      retries: 10